{$S-,R-,V-,I-,B-,F-}

{$M 8192,32767,655360}

{*********************************************************}
{*                  MAKESCRN.PAS 1.30                    *}
{*     Copyright (c) TurboPower Software 1989, 1992.     *}
{*                 All rights reserved.                  *}
{*********************************************************}

program MakeScreen;
  {-Data entry screen designer for Object Professional 1.0}

uses
  msmain; {<- actual MAKESCRN code is in here}

begin
  Main;
end.
